MilkBot/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MilkBot.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

MilkBot/Controllers/TextUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.MemoryMappedFiles;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using StackExchange.Redis;

namespace MilkBot.Controllers
{
    public class TextUploadController : ApiController
    {
        public ConnectionMultiplexer ConnectionMultiplexer { get; set; }

        [Route("TextUpload/Upload")]
        [HttpPost]
        public async Task<IHttpActionResult> Upload()
        {
            if (!Request.Content.IsMimeMultipartContent())
                throw new Exception(); // divided by zero

            var provider = new MultipartMemoryStreamProvider();
            await Request.Content.ReadAsMultipartAsync(provider);

            foreach (var file in provider.Contents)
            {
                var filename = file.Headers.ContentDisposition.FileName.Trim('\"');

                if (file.Headers.ContentType.MediaType != MediaTypeNames.Text.Plain) {
                    return BadRequest("Invalid file type. Only plain-text files are allowed.");
                }
                var buffer = await file.ReadAsStringAsync();

                var cache = ConnectionMultiplexer.GetDatabase();
                var markovChainCreator = new MarkovChainCreator(cache);
                var numWordsAdded = markovChainCreator.LoadTextWithSentences(buffer);
                return Ok(numWordsAdded);
            }

            return Ok();
        }
    }
}

MilkBot/Views/Home/Index.cshtml
<div class="jumbotron">
    Upload a text file to incorporate into <em>the brain</em>.
</div>
@using (@Html.BeginForm("Upload", "TextUpload", FormMethod.Post, new {@enctype = "multipart/form-data"})) {
    @Html.ValidationSummary()
    <div>
        <label for="textFileUpload">Text File</label>
        <input name="textFileUpload" id="textFileUpload" type="file" />
    </div>
    <div>
        <input type="button" id="Upload" value="Upload" />
    </div>
    <div id="messages"></div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#Upload').click(function () {
            var formData = new FormData();
            var opmlFile = $('#textFileUpload')[0];
            formData.append("opmlFile", opmlFile.files[0]);

            $(this).attr('disabled', 'disabled');
            $.ajax({
                url: '/TextUpload/Upload',
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false
            })
            .done(function(data) {
                $(this).attr('disabled', 'enabled');

                $("#messages").append("<br>" + $("#textFileUpload").val() + " has been added to the brain! " + data + " words have been added.");
            });
        });
    });
</script>